[package]
name = "thread_pool"
version = "0.1.0"
edition = "2021"
authors = ["Oldcat <924417424@qq.com>"]
description = "这是一个简易的线程池实现"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
